name: 'Generate macOS Installer'
description: 'This action creates an installer (.pkg) for macOS.'
inputs:
  output-directory:
    description: >
      Specifies the output directory.
      If omitted, runner.temp is set.
    required: false
    default: ${{ runner.temp }}
  root-directory:
    description: >
      The root path of the directory containing the set of resources to be bundled.
    required: true
  bundle-path:
    description: >
      Specify the relative path of *.app to be placed under the directory specified in 'root-directory' as the base point.
    required: true
  identifier:
    description: >
      Specify the application ID.
    required: true
  version:
    description: >
      Specifies the version of the package to be created.
      If omitted, github.run_number is set.
    required: true
    default: ${{ github.run_number }}
  install-location:
    description: >
      The directory where the package is to be installed.
      If omitted, '/Applications' is specified.
    required: false
    default: /Applications
  scripts-directory:
    description: >
      The directory passed to --scripts, e.g. for preinstall and postinstall.
      If omitted, --script is not passed.
    required: false
outputs:
  output-path:
    description: >
      The output path of the package.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: "box"
  color: "orange"