name: Test

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize

jobs:
  Test:
    runs-on: macos-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4

      - uses: ./
        id: mac-installer
        with:
          root-directory: Artifacts
          bundle-path: Build.app
          identifier: com.akiojin.GitHubActionsForUnity
          version: ${{ github.run_number }}